# Project: ÏîÄ¿1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = csim.o cachelab.o
LINKOBJ  = csim.o cachelab.o
LIBS     = -L"E:/Dev-c++/Dev-Cpp/MinGW64/lib" -L"E:/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"E:/Dev-c++/Dev-Cpp/MinGW64/include" -I"E:/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Dev-c++/Dev-Cpp/MinGW64/include" -I"E:/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = A.exe
CXXFLAGS = $(CXXINCS) -g3 -O2
CFLAGS   = $(INCS) -g3 -O2
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

csim.o: csim.c
	$(CC) -c csim.c -o csim.o $(CFLAGS)

cachelab.o: cachelab.c
	$(CC) -c cachelab.c -o cachelab.o $(CFLAGS)
